import {
  Anchor, Bike, Bird, BookOpen, Cake, Camera, Car, Coffee, Cross, Feather, Film, Fish, Flame, Flower2, Gamepad2, Guitar, Heart, Home, Leaf, Moon, Mountain, Music, PawPrint, Piano, Plane, Rainbow, Rocket, Sailboat, Sparkles, Sprout, Sun, TreePine, Trophy, Waves, Wine,
  type LucideIcon,
} from "lucide-react";
import type { MotifKey } from "@/lib/appearance";

/** Icon for each motif key. Kept out of lib/appearance so the server action does not pull in the icon set. */
export const MOTIF_ICONS: Record<MotifKey, LucideIcon> = {
  flowers: Flower2,
  dove: Bird,
  stars: Sparkles,
  candle: Flame,
  leaves: Leaf,
  music: Music,
  heart: Heart,
  waves: Waves,
  sun: Sun,
  moon: Moon,
  butterfly: Sparkles,
  anchor: Anchor,
  paw: PawPrint,
  trophy: Trophy,
  guitar: Guitar,
  plane: Plane,
  fish: Fish,
  pine: TreePine,
  mountain: Mountain,
  camera: Camera,
  book: BookOpen,
  coffee: Coffee,
  car: Car,
  cross: Cross,
  rainbow: Rainbow,
  cake: Cake,
  rocket: Rocket,
  feather: Feather,
  wine: Wine,
  home: Home,
  film: Film,
  gamepad: Gamepad2,
  sprout: Sprout,
  bike: Bike,
  sailboat: Sailboat,
  piano: Piano,
};
